Fix shader compilation error
This fixes the following error:
[Shader] Warning: [GLSL-SO::CompileShaderObject] shader-object name: GLSL/ShadowGenFragProg.glsl, compile-log:
0(13) : error C5514: 'varying' is deprecated and removed from this profile, use 'in/out' instead
0(14) : error C5514: 'varying' is deprecated and removed from this profile, use 'in/out' instead
0(15) : error C5514: 'varying' is deprecated and removed from this profile, use 'in/out' instead

It should be reverted when migrating to spring-106.0, as the shader is
fixed in that engine version.